"""
Empirical Challenger Test Suite (challenger_m1_2)
Focus: Clash Meta YAML and Streisand Base64 bundles generated by subjson-service/app.py
Verifies:
1. Mihomo binary validation (v2rayN/bin/bin/mihomo/mihomo.exe -t -f <file>)
2. Streisand Base64 decoding and strict URI parameter parsing (pbk, sid, sni, flow, obfs, etc.)
3. Fallback YAML generator vs PyYAML validation with Mihomo
4. Adversarial edge cases: extreme IDs, nonexistent clients, Cyrillic remarks/tags, expired/disabled states
"""

import base64
import copy
import json
import os
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import time
import unittest
import urllib.parse

# Setup environment before importing app
os.environ["HYSTERIA_SALAMANDER_PASSWORD"] = "485a96779d1ad79d0fa80ca0"  # PLACEHOLDER
os.environ["HYSTERIA_AUTH_PASSWORD"] = "test_auth_pass_443"  # PLACEHOLDER
os.environ["SECRET_SEGMENT"] = "test-secret"  # PLACEHOLDER
os.environ["INTERNAL_SECRET"] = "internal-token-xyz"  # PLACEHOLDER
os.environ["RELAY_PUBLIC_HOST"] = "relay.example.com"
os.environ["LISTEN_PORT"] = "3088"
os.environ["PUBLIC_HOST"] = "sub.example.com"
os.environ["PUBLIC_SUBSCRIPTION_ORIGIN"] = "https://sub.example.com"

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

APP_DIR = os.path.join(PROJECT_ROOT, "subjson-service")
if APP_DIR not in sys.path:
    sys.path.insert(0, APP_DIR)

MIHOMO_PATH = os.path.join(PROJECT_ROOT, "v2rayN", "bin", "bin", "mihomo", "mihomo.exe")
TEST_DB_PATH = os.path.join(PROJECT_ROOT, "бэкапы_баз_данных", "x-ui-test.db")
os.environ["XUI_DB_PATH"] = TEST_DB_PATH
os.environ["PUBLIC_HOST"] = "sub.example.com"
os.environ["WS443_PUBLIC_HOST"] = "edge.example.com"
os.environ["FI_STANDBY_HOST"] = "fi.example.com"

import app as subjson_app
import yaml


class EmpiricalChallengerTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not os.path.exists(MIHOMO_PATH):
            raise unittest.SkipTest(f"Mihomo binary not found at {MIHOMO_PATH}")

        # Setup an isolated test DB in tempdir
        cls.temp_dir = tempfile.mkdtemp(prefix="challenger_test_")
        cls.db_path = os.path.join(cls.temp_dir, "x-ui-test.db")
        cls.shop_db_path = os.path.join(cls.temp_dir, "vpn_shop.db")

        # Copy existing test db or create synthetic
        if os.path.exists(TEST_DB_PATH):
            shutil.copyfile(TEST_DB_PATH, cls.db_path)
        else:
            conn_xui = sqlite3.connect(cls.db_path)
            conn_xui.execute("""
                CREATE TABLE inbounds (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER,
                    up INTEGER,
                    down INTEGER,
                    total INTEGER,
                    remark TEXT,
                    enable INTEGER,
                    expiry_time INTEGER,
                    listen TEXT,
                    port INTEGER,
                    protocol TEXT,
                    settings TEXT,
                    stream_settings TEXT,
                    tag TEXT,
                    sniffing TEXT
                )
            """)
            settings_json = json.dumps({
                "clients": [
                    {
                        "id": "034d060d-8f33-4280-b22c-6b128813646f",
                        "email": "MainDefConf",
                        "limitIp": 0,
                        "totalGB": 0,
                        "expiryTime": 0,
                        "enable": True,
                        "tgId": "",
                        "subId": "MainDefConf",
                        "reset": 0
                    }
                ]
            })
            conn_xui.execute("""
                INSERT INTO inbounds (id, user_id, up, down, total, remark, enable, expiry_time, listen, port, protocol, settings, stream_settings, tag, sniffing)
                VALUES (2, 1, 0, 0, 0, 'tcp-inbound', 1, 0, '0.0.0.0', 443, 'vless', ?, '{}', 'inbound-443', '{}')
            """, (settings_json,))
            conn_xui.commit()
            conn_xui.close()
        subjson_app.XUI_DB_PATH = cls.db_path
        os.environ["XUI_DB_PATH"] = cls.db_path
        os.environ["STORE_DB_PATH"] = cls.shop_db_path

        # Populate shop db
        conn = sqlite3.connect(cls.shop_db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS profiles (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                public_id TEXT UNIQUE,
                xui_inbound_id INTEGER,
                transport TEXT,
                profile_mode TEXT,
                family_label TEXT,
                xui_email TEXT,
                xui_client_id TEXT,
                status TEXT,
                created_at INTEGER,
                expires_at INTEGER,
                last_renewed_at INTEGER,
                deleted_at INTEGER,
                notes TEXT
            )
        """)
        now = int(time.time())
        conn.execute("""
            INSERT INTO profiles (public_id, xui_inbound_id, transport, profile_mode, xui_email, xui_client_id, status, created_at, expires_at)
            VALUES ('prf_active1', 2, 'tcp', 'anonymous', 'MainDefConf', '034d060d-8f33-4280-b22c-6b128813646f', 'active', ?, ?)
        """, (now, now + 30 * 86400))
        conn.execute("""
            INSERT INTO profiles (public_id, xui_inbound_id, transport, profile_mode, xui_email, xui_client_id, status, created_at, expires_at)
            VALUES ('prf_expired1', 2, 'tcp', 'anonymous', 'ExpiredUser', '11111111-2222-3333-4444-555555555555', 'active', ?, ?)
        """, (now - 10000, now - 5000))
        conn.commit()
        conn.close()

        # Add expired client to x-ui db
        xconn = sqlite3.connect(cls.db_path)
        inb = xconn.execute("SELECT id, settings FROM inbounds WHERE id = 2").fetchone()
        if inb:
            st = json.loads(inb[1])
            st["clients"].append({
                "id": "11111111-2222-3333-4444-555555555555",
                "flow": "xtls-rprx-vision",
                "email": "ExpiredUser",
                "limitIp": 0,
                "totalGB": 0,
                "expiryTime": (now - 5000) * 1000,
                "enable": True,
                "tgId": "",
                "subId": "expired-sub-id",
            })
            # Add a disabled client
            st["clients"].append({
                "id": "22222222-3333-4444-5555-666666666666",
                "flow": "xtls-rprx-vision",
                "email": "DisabledUser",
                "limitIp": 0,
                "totalGB": 0,
                "expiryTime": (now + 86400) * 1000,
                "enable": False,
                "tgId": "",
                "subId": "disabled-sub-id",
            })
            xconn.execute("UPDATE inbounds SET settings = ? WHERE id = 2", (json.dumps(st),))
            xconn.commit()
        xconn.close()

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.temp_dir, ignore_errors=True)

    def _run_mihomo_validate(self, yaml_content: str) -> subprocess.CompletedProcess:
        """Runs mihomo.exe -t -f <temp_yaml> and returns completed process."""
        temp_yaml = os.path.join(self.temp_dir, f"test_clash_{time.time_ns()}.yaml")
        with open(temp_yaml, "w", encoding="utf-8") as f:
            f.write(yaml_content)

        res = subprocess.run(
            [MIHOMO_PATH, "-t", "-f", temp_yaml],
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=10,
        )
        return res

    # ==========================================
    # 1. MIHOMO CORE EMPIRICAL CHALLENGE TESTS
    # ==========================================

    def test_01_empirical_bug_reproduction_geosite_ru_failure(self):
        """Verify build_clash_meta_config in split-ru mode no longer has GEOSITE,ru and passes Mihomo validation."""
        yaml_out = subjson_app.build_clash_meta_config("MainDefConf", "sub.example.com", "split-ru")
        self.assertNotIn("GEOSITE,ru,DIRECT", yaml_out)
        res = self._run_mihomo_validate(yaml_out)
        self.assertEqual(res.returncode, 0, f"Mihomo validation failed on split-ru mode:\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}")
        self.assertIn("test is successful", res.stdout.lower())

    def test_02_mihomo_validation_active_global(self):
        """Empirically test Clash Meta YAML with Mihomo core (global route mode)."""
        yaml_out = subjson_app.build_clash_meta_config("MainDefConf", "sub.example.com", "global")
        res = self._run_mihomo_validate(yaml_out)
        self.assertEqual(res.returncode, 0, f"Mihomo validation failed on global mode:\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}")
        self.assertIn("configuration file", res.stdout.lower())
        self.assertIn("test is successful", res.stdout.lower())

    def test_03_mihomo_validation_expired_sub(self):
        """Empirically test Clash Meta YAML for expired subscription with Mihomo core."""
        yaml_out = subjson_app.build_clash_meta_config("expired-sub-id", "sub.example.com", "split-ru")
        parsed = yaml.safe_load(yaml_out)
        self.assertEqual(parsed.get("mode"), "direct")
        self.assertEqual(parsed.get("proxies"), [])

        res = self._run_mihomo_validate(yaml_out)
        self.assertEqual(res.returncode, 0, f"Mihomo validation failed on expired sub:\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}")

    def test_04_mihomo_validation_split_ru_with_fixed_rules(self):
        """Verify that removing GEOSITE,ru from split-ru rules makes Mihomo pass completely."""
        yaml_out = subjson_app.build_clash_meta_config("MainDefConf", "sub.example.com", "split-ru")
        parsed = yaml.safe_load(yaml_out)

        # Remove the offending GEOSITE,ru rule
        parsed["rules"] = [r for r in parsed["rules"] if r != "GEOSITE,ru,DIRECT"]
        fixed_yaml = yaml.dump(parsed, allow_unicode=True, sort_keys=False)

        res = self._run_mihomo_validate(fixed_yaml)
        self.assertEqual(res.returncode, 0, f"Mihomo failed on fixed split-ru rules:\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}")
        self.assertIn("test is successful", res.stdout.lower())

    def test_05_mihomo_validation_fallback_yaml_generator(self):
        """Empirically test custom fallback YAML serializer when yaml module is bypassed."""
        yaml_out = subjson_app.build_clash_meta_config("MainDefConf", "sub.example.com", "global")
        doc = yaml.safe_load(yaml_out)

        # Monkeypatch yaml module import failure inside dump_clash_yaml
        orig_yaml = sys.modules.get("yaml")
        try:
            sys.modules["yaml"] = None
            fallback_yaml = subjson_app.dump_clash_yaml(doc)
        finally:
            if orig_yaml is not None:
                sys.modules["yaml"] = orig_yaml

        res = self._run_mihomo_validate(fallback_yaml)
        self.assertEqual(res.returncode, 0, f"Mihomo validation failed on fallback YAML generator:\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}")

    # ==========================================
    # 2. CLASH META STRUCTURE & PARITY TESTS
    # ==========================================

    def test_06_clash_proxy_groups_and_proxies_integrity(self):
        """Verify all 10 proxies and 3 proxy-groups are present with correct parameters."""
        yaml_out = subjson_app.build_clash_meta_config("MainDefConf", "sub.example.com", "global")
        parsed = yaml.safe_load(yaml_out)

        proxies = parsed.get("proxies", [])
        self.assertEqual(len(proxies), 10, f"Expected 10 proxies, found {len(proxies)}")

        proxy_names = [p["name"] for p in proxies]
        expected_names = [
            "🇳🇱 NL Classic Reality TCP",
            "🇳🇱 NL Fast Reality TCP",
            "🇳🇱 NL Speed Hysteria2",
            "🇳🇱 NL Backup Reality gRPC",
            "🇳🇱 NL Stealth XHTTP",
            "🇫🇮 FI Classic Reality TCP",
            "🇫🇮 FI Fast Reality TCP",
            "🇫🇮 FI Speed Hysteria2",
            "🇫🇮 FI Backup Reality gRPC",
            "🇫🇮 FI Stealth XHTTP Reality",
        ]
        self.assertEqual(proxy_names, expected_names)

        # Check FI XHTTP Reality port & Reality params
        fi_xhttp = next(p for p in proxies if p["name"] == "🇫🇮 FI Stealth XHTTP Reality")
        self.assertEqual(fi_xhttp["port"], subjson_app.FI_XHTTP_REALITY_PORT)
        self.assertEqual(fi_xhttp["servername"], subjson_app.FI_XHTTP_REALITY_SNI)
        self.assertEqual(fi_xhttp["reality-opts"]["public-key"], subjson_app.FI_XHTTP_REALITY_PUBLIC_KEY)
        self.assertEqual(fi_xhttp["reality-opts"]["short-id"], subjson_app.FI_XHTTP_REALITY_SHORT_ID)

        # Check Hysteria2 Salamander Obfs
        nl_hy2 = next(p for p in proxies if p["name"] == "🇳🇱 NL Speed Hysteria2")
        self.assertEqual(nl_hy2["type"], "hysteria2")
        self.assertEqual(nl_hy2["obfs"], "salamander")
        self.assertEqual(nl_hy2["obfs-password"], "485a96779d1ad79d0fa80ca0")

        # Check Proxy Groups
        groups = {g["name"]: g for g in parsed.get("proxy-groups", [])}
        self.assertIn("🚀 PROXY", groups)
        self.assertIn("⚡ Auto URL-Test", groups)
        self.assertIn("🛡️ Priority Fallback", groups)

        urltest = groups["⚡ Auto URL-Test"]
        self.assertEqual(urltest["type"], "url-test")
        self.assertEqual(urltest["url"], "https://cp.cloudflare.com/generate_204")
        self.assertEqual(urltest["interval"], 180)
        self.assertEqual(urltest["tolerance"], 50)
        self.assertEqual(urltest["expected-status"], "204")
        self.assertTrue(urltest["lazy"])

        fallback = groups["🛡️ Priority Fallback"]
        self.assertEqual(fallback["type"], "fallback")
        self.assertEqual(fallback["url"], "https://cp.cloudflare.com/generate_204")
        self.assertEqual(fallback["interval"], 180)
        self.assertEqual(fallback["expected-status"], "204")
        self.assertTrue(fallback["lazy"])

    # ==========================================
    # 3. STREISAND BASE64 & URI PARSING TESTS
    # ==========================================

    def test_07_streisand_base64_decode_and_param_validation(self):
        """Decode Streisand Base64 and parse all URIs & query parameters."""
        b64_str = subjson_app.build_streisand_bundle("MainDefConf", "sub.example.com")
        self.assertTrue(len(b64_str) > 100, "Base64 bundle is too short")

        raw_text = base64.b64decode(b64_str).decode("utf-8")
        lines = [line.strip() for line in raw_text.splitlines() if line.strip()]
        self.assertEqual(len(lines), 10, f"Expected 10 URIs, got {len(lines)}")

        parsed_uris = []
        for line in lines:
            parsed = urllib.parse.urlparse(line)
            qs = urllib.parse.parse_qs(parsed.query)
            tag = urllib.parse.unquote(parsed.fragment)
            parsed_uris.append({
                "scheme": parsed.scheme,
                "netloc": parsed.netloc,
                "hostname": parsed.hostname,
                "port": parsed.port,
                "username": parsed.username,
                "query": qs,
                "tag": tag,
            })

        # URI 0: NL Classic Reality TCP
        u0 = parsed_uris[0]
        self.assertEqual(u0["scheme"], "vless")
        self.assertEqual(u0["hostname"], "edge.example.com")
        self.assertEqual(u0["port"], 443)
        self.assertEqual(u0["query"]["type"][0], "tcp")
        self.assertEqual(u0["query"]["security"][0], "reality")
        self.assertEqual(u0["query"]["pbk"][0], subjson_app.TCP_REALITY_PUBLIC_KEY)
        self.assertEqual(u0["query"]["sid"][0], subjson_app.TCP_REALITY_SHORT_ID)
        self.assertEqual(u0["query"]["flow"][0], "xtls-rprx-vision")
        self.assertEqual(u0["query"]["sni"][0], "sber.ru")
        self.assertIn("🇳🇱 1. Классический TCP (NL)", u0["tag"])

        # URI 2: NL Speed Hysteria2
        u2 = parsed_uris[2]
        self.assertEqual(u2["scheme"], "hy2")
        self.assertEqual(u2["hostname"], "sub.example.com")
        self.assertEqual(u2["port"], 443)
        self.assertEqual(u2["query"]["sni"][0], "sub.example.com")
        self.assertEqual(u2["query"]["alpn"][0], "h3")
        self.assertEqual(u2["query"]["obfs"][0], "gecko")
        self.assertEqual(u2["query"]["obfs-password"][0], "485a96779d1ad79d0fa80ca0")
        self.assertIn("🇳🇱 3. Скоростной Hysteria2 (NL)", u2["tag"])

        # URI 3: NL Backup Reality gRPC
        u3 = parsed_uris[3]
        self.assertEqual(u3["scheme"], "vless")
        self.assertEqual(u3["hostname"], "edge.example.com")
        self.assertEqual(u3["port"], 29443)
        self.assertEqual(u3["query"]["type"][0], "grpc")
        self.assertEqual(u3["query"]["security"][0], "reality")
        self.assertEqual(u3["query"]["serviceName"][0], "grpc-maxru")

        # URI 9: FI Stealth XHTTP Reality
        u9 = parsed_uris[9]
        self.assertEqual(u9["scheme"], "vless")
        self.assertEqual(u9["hostname"], "fi.example.com")
        self.assertEqual(u9["port"], subjson_app.FI_XHTTP_REALITY_PORT)
        self.assertEqual(u9["query"]["type"][0], "xhttp")
        self.assertEqual(u9["query"]["security"][0], "reality")
        self.assertEqual(u9["query"]["pbk"][0], subjson_app.FI_XHTTP_REALITY_PUBLIC_KEY)
        self.assertEqual(u9["query"]["sid"][0], subjson_app.FI_XHTTP_REALITY_SHORT_ID)
        self.assertEqual(u9["query"]["sni"][0], subjson_app.FI_XHTTP_REALITY_SNI)
        self.assertIn("🇫🇮 10. Незаметный XHTTP Reality (FI)", u9["tag"])

    def test_08_streisand_expired_sub_empty_bundle(self):
        """Streisand bundle for expired subscription returns empty Base64."""
        b64_str = subjson_app.build_streisand_bundle("expired-sub-id", "sub.example.com")
        self.assertEqual(b64_str, "")

    # ==========================================
    # 4. ADVERSARIAL EDGE CASES & STRESS HARNESS
    # ==========================================

    def test_09_adversarial_cyrillic_remarks_and_tags(self):
        """Verify URI fragment encoding handles Cyrillic, emoji flags, and special characters cleanly."""
        b64_str = subjson_app.build_streisand_bundle("MainDefConf", "sub.example.com")
        raw = base64.b64decode(b64_str).decode("utf-8")
        for line in raw.splitlines():
            fragment = line.split("#", 1)[1] if "#" in line else ""
            unquoted = urllib.parse.unquote(fragment)
            self.assertTrue(len(unquoted) > 0)
            self.assertTrue("🇳🇱" in unquoted or "🇫🇮" in unquoted)

    def test_10_adversarial_nonexistent_sub_id(self):
        """Nonexistent sub ID generates syntactically valid configs using fallback UUID."""
        nonexistent_id = "nonexistent-client-id-xyz-999"
        # 1. Clash Meta (global mode test)
        yaml_out = subjson_app.build_clash_meta_config(nonexistent_id, "sub.example.com", "global")
        res = self._run_mihomo_validate(yaml_out)
        self.assertEqual(res.returncode, 0, f"Mihomo validation failed on nonexistent sub_id:\n{res.stdout}\n{res.stderr}")

        # 2. Streisand
        b64_out = subjson_app.build_streisand_bundle(nonexistent_id, "sub.example.com")
        raw = base64.b64decode(b64_out).decode("utf-8")
        lines = [l for l in raw.splitlines() if l.strip()]
        self.assertEqual(len(lines), 10)
        self.assertIn(nonexistent_id, lines[0])

    def test_11_adversarial_extreme_subscription_ids(self):
        """Stress-test extreme subscription IDs: long strings, unicode, SQL chars, spaces."""
        extreme_cases = [
            "a" * 500,  # 500 char string
            "user~hybrid~token~123",  # hybrid tilde delimiter
            "тест_пользователь_кириллица",  # Russian characters
            "id-with-'single-quotes'-and-\"double-quotes\"",  # Quotes
            "id-with-colon:and#hash?query=1&amp=2",  # URL characters
            "   padded_with_whitespace   ",  # Leading/trailing whitespace
        ]

        for case in extreme_cases:
            with self.subTest(extreme_sub_id=case):
                # 1. Clash Meta YAML (using global mode to isolate sub_id formatting from rules bug)
                yaml_out = subjson_app.build_clash_meta_config(case, "sub.example.com", "global")
                self.assertTrue(len(yaml_out) > 200)

                res = self._run_mihomo_validate(yaml_out)
                self.assertEqual(res.returncode, 0, f"Mihomo failed on sub ID '{case[:30]}': {res.stdout} {res.stderr}")

                # 2. Streisand Base64
                b64_out = subjson_app.build_streisand_bundle(case, "sub.example.com")
                raw = base64.b64decode(b64_out).decode("utf-8")
                lines = [l for l in raw.splitlines() if l.strip()]
                self.assertEqual(len(lines), 10)

    def test_12_adversarial_streisand_unpadded_base64_decoding(self):
        """Verify decoder handles unpadded Base64 bundles gracefully."""
        b64_str = subjson_app.build_streisand_bundle("MainDefConf", "sub.example.com")
        unpadded = b64_str.rstrip("=")
        missing = len(unpadded) % 4
        padded = unpadded + ("=" * (4 - missing) if missing else "")
        raw = base64.b64decode(padded).decode("utf-8")
        self.assertEqual(len([l for l in raw.splitlines() if l.strip()]), 10)


if __name__ == "__main__":
    unittest.main(verbosity=2)
